#eThe URL the site will be built for
base_url = "https://lm41.github.io"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
theme = "duckquill"
build_search_index = false

# Languages
default_language = "en"
title = "FlorisBoard"
description = "An open-source keyboard for Android which respects your privacy. Currently in early-beta."

[languages.es]
title = "FlorisBoard"
description = "Un teclado libre para Android que respeta tu privacidad. Actualmente en beta temprana."

[languages.fr]
title = "FlorisBoard"
description = "Un teclado libre para Android que respeta tu privacidad. Actualmente en beta temprana."

[markdown]
highlight_code = false
external_links_target_blank = true

[extra]
styles = ["mods.css"]
default_theme = "system"
accent_color = "#25a841"
accent_color_dark = "#0de03b"
favicon = "static/favicon.png"
source_url = "https://github.com/florisboard/florisboard"

toc = false
toc_inline = false

[extra.nav]
show_theme_switcher = true
show_repo = true

links = [
  { url = "@/installation/_index.md", name = "Installation"},
  { url = "@/legal/privacy/_index.md", name = "Legal" },
  { url = "https://beta.addons.florisboard.org", name = "Addons"}
]

[extra.footer]
links = [
  { url = "@/installation/_index.md", name = "Installation"},
  { url = "@/legal/privacy/_index.md", name = "Legal" },
  { url = "https://beta.addons.florisboard.org", name = "Addons"}
]
socials = [
	{ url = "https://github.com/florisboard/florisboard", name = "GitHub", icon = "%3Csvg role='img' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3EGitHub%3C/title%3E%3Cpath d='M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12'/%3E%3C/svg%3E" }
]
show_copyright = true
copyright = "© `2020-2025` [The FlorisBoard Contributors](https://github.com/florisboard/florisboard/graphs/contributors)"

show_powered_by = true

