# baseURL = "https://florisboard.org/"
baseURL = "https://delthia.github.io/florisboard.github.io/"
defaultContentLanguage = 'en'
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
assetDir = "src"
enableRobotsTXT = true

title = "FlorisBoard"


[languages]
    [languages.en]
        description = "An open-source keyboard for Android which respects your privacy. Currently in early-beta."
        weight = 1
        languageCode = "en-US"
        gh-repo = "Visit GitHub repo"
        privacy = "Privacy Policy"
        not-found = "The requested resource could not be found. Please check the address and try again."
    [languages.es]
        description = "Un teclado libre para Android que respeta tu privacidad. Actualmente en beta temprana."
        weight = 2
        languageCode = "es-ES"
        gh-repo = "Visitar el repositorio de GitHub"
        privacy = "Política de privacidad"
        not-found = "No se pudo encontrar el recurso solicitado. Por favor, comprueba la dirección y prueba otra vez."
