name: Deploy www module to florisboard.org

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy_www.yml"
      - ".gitmodules"
      - "www/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

# TODO: deploy to server instead of GH pages
jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5.0.0
    - name: Build only
      uses: shalzz/zola-deploy-action@v0.21.0
      env:
        BUILD_DIR: www
        BUILD_ONLY: true
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
