name: Deploy schemas module to schemas.florisboard.org

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy_schemas.yml"
      - "schemas/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup SSH
        run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.FLPAGES_DEPLOY_KEY_SSH }}" > "$HOME/.ssh/id_ed25519"
          chmod 600 "$HOME/.ssh/id_ed25519"
          ssh-keyscan -H schemas.florisboard.org >> "$HOME/.ssh/known_hosts"
      - name: Copy schemas to server
        run: rsync -r schemas/* deploy@schemas.florisboard.org:/srv/schemas/

